152.58.45.24 - - [08/Oct/2025 00:39:01] "GET /home.html HTTP/1.1" 200 -
152.58.45.24 - - [08/Oct/2025 00:39:04] code 404, message File not found
152.58.45.24 - - [08/Oct/2025 00:39:04] "GET /assets/images/67917ae8f7c29db00d3801a8_rail%20video%203-poster-00001.jpg HTTP/1.1" 404 -
152.58.45.24 - - [08/Oct/2025 00:39:05] code 404, message File not found
152.58.45.24 - - [08/Oct/2025 00:39:05] "GET /assets/images/67917adff66792c665b8c1a9_rail%20video%202-poster-00001.jpg HTTP/1.1" 404 -
152.58.45.24 - - [08/Oct/2025 00:39:06] code 404, message File not found
152.58.45.24 - - [08/Oct/2025 00:39:06] "GET /assets/images/67917ac8f5c215b9e436c24a_rail%20video%201-poster-00001.jpg HTTP/1.1" 404 -
152.58.45.24 - - [08/Oct/2025 00:39:21] "GET /rail-payment-clients-100-localized.html HTTP/1.1" 200 -
152.58.45.24 - - [08/Oct/2025 00:39:27] code 404, message File not found
152.58.45.24 - - [08/Oct/2025 00:39:27] "GET /favicon.ico HTTP/1.1" 404 -
152.58.45.24 - - [08/Oct/2025 00:39:33] "GET /rail-banking-partners-100-localized.html HTTP/1.1" 200 -
152.58.45.24 - - [08/Oct/2025 00:39:43] "GET /rail-how-it-works-100-localized.html HTTP/1.1" 200 -
172.206.32.165 - - [08/Oct/2025 00:40:33] "GET /home.html HTTP/1.1" 200 -
172.206.32.165 - - [08/Oct/2025 00:40:33] "GET /home.html HTTP/1.1" 200 -
172.206.32.165 - - [08/Oct/2025 00:40:42] "GET /home.html HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.206.32.165', 53724)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
172.206.32.165 - - [08/Oct/2025 00:40:42] "GET /home.html HTTP/1.1" 200 -
172.206.32.165 - - [08/Oct/2025 00:40:51] "GET /home.html HTTP/1.1" 200 -
